name: Run Colab Notebook

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Cho phép chạy thủ công từ GitHub Actions
  schedule:
    - cron: '15 20 * * *'  # Lệnh cron để chạy tự động hàng ngày lúc 00:00 UTC

jobs:
  run_colab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install gdown  # Hoặc các gói bạn cần để chạy Colab notebook

      - name: Run Colab notebook
        run: |
          gdown --id <12umrh2-eZmnmxQuXb4tE9ZUToO137Hhd>.ipynb
          # Hoặc chạy script Python mà bạn muốn tự động hóa

  
