name: Run Colab Notebook

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Cho phép chạy thủ công từ GitHub Actions
  schedule:
    - cron: '30 15 * * *'  # Lệnh cron để chạy tự động hàng ngày lúc 00:00 UTC

jobs:
  run_colab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install gdown  # Hoặc các gói bạn cần để chạy Colab notebook

      - name: Download Colab Notebook
        run: |
          gdown --id 12umrh2-eZmnmxQuXb4tE9ZUToO137Hhd  # Tải notebook từ Google Drive bằng gdown

      - name: Run Colab notebook with papermill
        run: |
          papermill your_notebook.ipynb output.ipynb  # Chạy notebook bằng papermill và lưu kết quả vào output.ipynb
  
